# -*- coding: utf-8 -*-
"""3_EvidenciaFinal_A01734979.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SA1jrcDr8p2CwDZvgqTcHpPCPEmCQrSx
"""

import streamlit as st
import pandas as pd 
import numpy as np 
import plotly as px 
import plotly.figure_factory as ff
from bokeh.plotting import figure 
import matplotlib.pyplot as plt 

st.title('Police Incident Reports from 2018 to 2020 in San Francisco')
df = pd.read_csv("https://drive.google.com/file/d/1ioUp8979nNLh9h-CYVyJcRgAhxBhCLIm/view?usp=sharing")
st.markdown('The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.')

mapa = pd.DataFrame()
mapa['Date'] = df['Incident Date']
mapa['Day'] = df['Incident Day of Week']
mapa['Police District'] = df['Police District']
mapa['Neighborhood'] = df['Analysis Neighborhood']
mapa['Incident Category'] = df['Incident Category']
mapa['Incident Subcategory'] = df['Incident Subcategory']
mapa['Resolution'] = df['Resolution']

mapa['lat'] = df['Latitude']
mapa['lon'] = df['Longitude']
mapa=mapa.dropna()
st.map(mapa.astype(int))

#kjfkjsnkvjndfkjv